### ISSUE TITLE
Select front-end framework

### ISSUE THREAD

**Issue by zbuc** [kolide/queryhub#2]
A front-end JS framework will need to be used

**Comment by marpaia** [comment]
I started working towards this topic of stuff in #28. I'd be down to use React, but I would also be down to maybe try [Reason](https://reasonml.github.io/). I think a Reason/Elixir app might be a pretty slick, modern functional app setup.

**Comment by marpaia** [comment]
[Elm](http://elm-lang.org/) would also be cool, although both Facebook and Bloomberg backing Reason is a big value-add IMO.

**Comment by jordan-wright** [comment]
I'd personally err on the side of trying to re-use code where we can, while supporting the largest community of contributors where we can. Going the React route would allow us to re-use the components that have already been built for Fleet and the other misc. websites Kolide has created while being open to the already huge React community.

It's possible that I just don't hang around the functional lang community enough to understand how big it is so I could be wrong - I've just always been under the impression that the standard (Go + Python) / React/Vue/Angular community has always been a couple orders of magnitude bigger than the functional language community.

**Comment by zbuc** [comment]
Is this also a reason to consider adopting Go for the backend? It seems like we will have to reimplement things in Elixir that could be implemented in Golang libs shared across Fleet and QueryHub, for example parsing and validating the fleetctl YAML format.

**Comment by marpaia** [comment]
I love Go just as much as anyone, but IMO it's just not the most productive tool for the job when it comes to making websites that server-render content. There's [Buffalo](https://github.com/gobuffalo/buffalo), but a lot of the decisions that Buffalo forces you to make are less than ideal IMO. Alternatively, you can DIY and build out all of that yourself (like we did with Fleet) and while that works, it's not very productive.

**Comment by marpaia** [comment]
I added React in #28.
